name : Build

on: 
    push:
        branches:
            - main
        paths:
          - 'src/**'
          - 'package.json'
          - 'tsconfig.json'
          - 'Dockerfile'
          - 'docker-compose.yml'
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        env:
            NODE_VERSION : 18.x
            NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
            NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
            NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
            NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
            NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
            NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
            PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            PORT: ${{ secrets.PORT }}
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
            FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
            
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name : setup-node
              uses : actions/setup-node@v3
              with : 
                node-version: 18
            - name : Cache node_modules
              uses : actions/cache@v3
              with : 
                path : node_modules
                key : ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
                restore-keys : |
                    ${{ runner.os }}-node-
            - name : Install dependencies
              run : npm install
            - name : Validate
              run : npm run validate
            - name : Build
              run : npm run build
            - name: Build Docker image
              run: docker build -t test-image:ci .
            - name: Test Docker container health endpoint
              run: |
                echo "Starting Docker container for health check..."
                docker run -d -p 3000:3000 --name test_container \
                  -e NEXT_PUBLIC_FIREBASE_API_KEY="${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" \
                  -e NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" \
                  -e NEXT_PUBLIC_FIREBASE_PROJECT_ID="${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" \
                  -e NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" \
                  -e NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" \
                  -e NEXT_PUBLIC_FIREBASE_APP_ID="${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" \
                  -e NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}" \
                  -e PINECONE_API_KEY="${{ secrets.PINECONE_API_KEY }}" \
                  -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
                  -e PORT="${{ secrets.PORT }}" \
                  -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
                  -e FIREBASE_SERVICE_ACCOUNT="${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" \
                  -e EMAIL_USER="${{ secrets.EMAIL_USER }}" \
                  -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
                  -e WEBSITE_URL="${{ secrets.WEBSITE_URL }}" \
                  test-image:ci
                echo "Waiting for the app to start..."
                sleep 30
                echo "Checking / endpoint for HTTP 200..."
                STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/)
                if [ "$STATUS" != "200" ]; then
                  echo "/ endpoint did not return 200 (got $STATUS)"
                  echo "Container logs:"
                  docker logs test_container
                  docker stop test_container
                  docker rm test_container
                  exit 1
                fi
                echo "Health check passed! Stopping and removing container."
                docker stop test_container
                docker rm test_container
