name: Ping Render URLs

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping all Render URLs
        run: |
          echo "[$(date)] Starting ping..."

          URLS=(
            "https://remotestar-backend.onrender.com/"
            "https://remotestar-backend-7unh.onrender.com"
            "https://remotestar-backend-testing.onrender.com"
          )

          # Allow script to continue even if curl fails
          set +e

          for url in "${URLS[@]}"; do
            echo "Pinging $url"
            response=$(curl --silent --show-error --fail "$url" 2>&1)
            exit_code=$?
            if [ $exit_code -eq 0 ]; then
              echo "Response from $url: $response"
            else
              echo "Error pinging $url (code $exit_code): $response"
            fi
          done

          echo "[$(date)] Ping complete."
