name: Deploy to Production
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: govindup63/remotestar-backend:${{ github.sha }}
      - name: clone remotestar-staging-ops repo , update image tag and push tag
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://${PAT}@github.com/govindup63/remotestar-staging-ops.git
          cd remotestar-staging-ops
          sed -i 's|image: govindup63/remotestar-backend:.*|image: govindup63/remotestar-backend:${{ github.sha }}|' deployment-staging.yml
          sed -i 's|image: govindup63/remotestar-backend:.*|image: govindup63/remotestar-backend:${{ github.sha }}|' deployment-main.yml

          git config user.name "Github Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "updated image tag to ${{ github.sha }}"
          git push https://${{ secrets.PAT }}@github.com/govindup63/remotestar-staging-ops.git main
